version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: csgo-postgres
    restart: always
    environment:
      POSTGRES_USER: csgo
      POSTGRES_PASSWORD: csgo123
      POSTGRES_DB: mydb
    command: postgres -c 'password_encryption=md5'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: csgo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "7070:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
