DROP TABLE IF EXISTS openings CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS case_items CASCADE;
DROP TABLE IF EXISTS cases CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS rarity_enum;
DROP TYPE IF EXISTS wear_enum;
DROP TYPE IF EXISTS transaction_type;
